/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedItensRouteImport } from './routes/_authenticated/itens'
import { Route as AuthenticatedMontagemRouteImport } from './routes/_authenticated/montagem'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedItensIdRouteImport } from './routes/_authenticated/itens_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItensRoute = AuthenticatedItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMontagemRoute = AuthenticatedMontagemRouteImport.update({
  id: '/montagem',
  path: '/montagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensIdRoute = AuthenticatedItensIdRouteImport.update({
  id: '/itens_/$id',
  path: '/itens/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/itens': typeof AuthenticatedItensRoute
  '/montagem': typeof AuthenticatedMontagemRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/itens/$id': typeof AuthenticatedItensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/itens': typeof AuthenticatedItensRoute
  '/montagem': typeof AuthenticatedMontagemRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/itens/$id': typeof AuthenticatedItensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/itens': typeof AuthenticatedItensRoute
  '/_authenticated/montagem': typeof AuthenticatedMontagemRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/itens_/$id': typeof AuthenticatedItensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compras'
    | '/fornecedores'
    | '/itens'
    | '/montagem'
    | '/painel'
    | '/vendas'
    | '/itens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compras'
    | '/fornecedores'
    | '/itens'
    | '/montagem'
    | '/painel'
    | '/vendas'
    | '/itens/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/compras'
    | '/_authenticated/fornecedores'
    | '/_authenticated/itens'
    | '/_authenticated/montagem'
    | '/_authenticated/painel'
    | '/_authenticated/vendas'
    | '/_authenticated/itens_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens': {
      id: '/_authenticated/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof AuthenticatedItensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/montagem': {
      id: '/_authenticated/montagem'
      path: '/montagem'
      fullPath: '/montagem'
      preLoaderRoute: typeof AuthenticatedMontagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens_/$id': {
      id: '/_authenticated/itens_/$id'
      path: '/itens/$id'
      fullPath: '/itens/$id'
      preLoaderRoute: typeof AuthenticatedItensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedItensRoute: typeof AuthenticatedItensRoute
  AuthenticatedMontagemRoute: typeof AuthenticatedMontagemRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedItensIdRoute: typeof AuthenticatedItensIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedItensRoute: AuthenticatedItensRoute,
  AuthenticatedMontagemRoute: AuthenticatedMontagemRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedItensIdRoute: AuthenticatedItensIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
